### ISSUE TITLE
PMEM_CACHE_FLUSH error

### ISSUE THREAD

**Issue by noorzaie** [Zomato/AndroidPhotoFilters#10]
when I apply a filter on bitmap, android studio shows infinite messages like this :

`W/QualcommCameraHardware7225a: MemoryCacheFlush : fd 73 size 155648 PMEM_CACHE_FLUSH error Invalid argument (22)`

Is there any problem with this??

**Comment by varunest** [comment]
@noorzaie  Which device are you using for debugging?

**Comment by noorzaie** [comment]
@varunest I solved the problem. never mind.
