### ISSUE TITLE
How to filter Grayscale

### ISSUE THREAD

**Issue by hoanganhtuan95ptit** [Zomato/AndroidPhotoFilters#21]
I want to Grayscale my photo, can you give me solution to implement it, thanks
![Image of Yaktocat](https://www.javacodegeeks.com/wp-content/uploads/2013/10/effect_grayscale.png)

**Comment by varunest** [comment]
You can use **SaturationSubfilter** to grayscale any image.

**Comment by hoanganhtuan95ptit** [comment]
Thank you very much
