### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by ylogx** [Zomato/AndroidPhotoFilters#36]
With changes in the API from PR #35, we'll have to release a new version of the library.

@varunest How is the release uploaded right now? AFAIK it is from your account only. Is there a way to share access to release with more team members?

**Comment by varunest** [comment]
No. Anyone with this repository access can create releases. Releases are hosted [here](https://mvnrepository.com/artifact/com.github.zomato).

Can you please merge #37. I will create new release after.

**Comment by ylogx** [comment]
Released [v1.0.2](https://github.com/Zomato/AndroidPhotoFilters/releases/tag/v1.0.2). Thanks @varunest 🙂
