### ISSUE TITLE
Recyclerview Filtered Image Stretched.

### ISSUE THREAD

**Issue by RB4915** [Zomato/AndroidPhotoFilters#47]
Hi, this is very good library for filters and i use it, but when i select any photo and it reflect to recyclerview's item which is shows how image looks like after selecting this filter, that images stretched, i used center crop in item imageview but not worked.

Anyone who solved this issue please give me suggestion or solution for it.

Thanks

**Comment by PeredurOmega** [comment]
I had the same issue. I assumed you are using ThumbnailsManager and ThumbnailItem. Your issue is due to the fact that ThumbnailsManger is rescaling the bitmap when processing. The solution I found is very simple: Just don't use ThumbnailsMnager. For instance: In my code I have:
```
List<Filter> filters = FilterPack.getFilterPack(context.get());
for (Filter filter : filters) {
      ThumbnailItem tI = new ThumbnailItem();
      tI.filter = filter;
      tI.filterName = filter.getName();
      tI.image = tI.filter.processFilter(Bitmap.createBitmap(thumbImage));
      thumbnailItemList.add(tI);
}
```

**Comment by RB4915** [comment]
Thank you @PeredurOmega it solved the issue.
