### ISSUE TITLE
java.lang.IllegalArgumentException: The Path cannot loop back on itself. in ToneCurveSubfilter

### ISSUE THREAD

**Issue by madhavbansal23** [Zomato/AndroidPhotoFilters#6]
I added the following points in the ToneCurveSubfilter under the rgb part.

Filter myFilter = new Filter();
Point[] rgbKnots;
rgbKnots = new Point[5];
        rgbKnots[0] = new Point(0, 0);
        rgbKnots[1] = new Point(51, 152);
        rgbKnots[2] = new Point(73, 172);
        rgbKnots[3] = new Point(204, 219);
        rgbKnots[4] = new Point(255, 255);
myFilter.addSubFilter(new ToneCurveSubfilter(rgbKnots, null, null, null));
Bitmap outputImage = myFilter.process(inputImage);

The app crashes saying 

**java.lang.IllegalArgumentException: The Path cannot loop back on itself.
at android.view.animation.PathInterpolator.initPath(PathInterpolator.java:181)
at android.view.animation.PathInterpolator.<init>(PathInterpolator.java:61)
at com.zomato.photofilters.geometry.BezierSpline.getOutputPointsForNewerDevices(BezierSpline.java:61)**

I am new to android image processing and am not able to resolve the issue. Please help

**Comment by varunest** [comment]
Hi Madhav, 

This is happening because the spline curve generated using these points is overlapping on the Y axis. You can't try modifying your data set.

**Comment by nguyenthanhhaic** [comment]
@varunest 
I dont understand about overlapping on the Y axis. Could you explain more about this. I met the same error.

**Comment by varunest** [comment]
@nguyenthanhhaic 
The points provided in RGBKnots array are plotted on x-y plane. For every value of x in this graph the y value represents the modified output. So for this filter to work there shouldn't be two values of y at any given point in the plotted graph.

**Comment by nguyenthanhhaic** [comment]
@varunest 

Thank for your fast reply!!

I draw 2 knot in curve by GIMP
[0] and [3] is default
[1] is ok but it crashed when add knot [2]. all the knots is different x, y value.
blueKnots = new Point[4];
        blueKnots[0] = new Point(0, 0);
        blueKnots[1] = new Point(150, 238);
        blueKnots[2] = new Point(40, 68);
        blueKnots[3] = new Point(255, 255);

as you explain. I can draw 1 knot[1] with 2 default knots [0]and [3]? should not add knot[2]?
