### ISSUE TITLE
Black & White and Sepia Tone

### ISSUE THREAD

**Issue by emreaktrk** [Zomato/AndroidPhotoFilters#7]
Hi,

Thanks for library. Its really great. I am bad at image skills. Can you please provide b&w and sepia effect? I cant figure out to how to do it with given sub filters.

Thanks

**Comment by varunest** [comment]
Hi, 

Those effects are not included in the library at present. We will try to add them in the next update.

**Comment by emreaktrk** [comment]
Thanks :+1:

**Comment by rcpassos** [comment]
Hi,

Any news about the new filters? :)

Thanks

**Comment by emreaktrk** [comment]
**For B&W:**

```
f1.mFilter = new Filter();
        f1.mFilter.addSubFilter(new SaturationSubfilter(-100f));
        FilterManager.add(f1);
```

**For Sephia**

`f2.mFilter = new Filter();
        f2.mFilter.addSubFilter(new SaturationSubfilter(-100f));
        f2.mFilter.addSubFilter(new ColorOverlaySubfilter(1, 102, 51, 0));`
